import "primereact/resources/themes/tailwind-light/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

import { store } from "@/redux/store";
import { Providers } from "./Provider/Provider";

import LayoutWrapper from "./layoutwrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Solar Academy",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	
	return (
		<Providers>
			<html lang="en">
				<body className={inter.className}>
					<LayoutWrapper>{children}</LayoutWrapper>
				</body>
			</html>
		</Providers>
	);
}
